### ISSUE TITLE
Rabbitvcs keeps asking for username/password on each commit, using it under Atom Editor

### ISSUE THREAD

**Issue by jcerdan** [rabbitvcs/rabbitvcs#270] opened 2019-06-18 10:10 UTC
Hi,
I'm using RabbitVCS under Atom Editor, where I use it for several projects.
After setting the message RabbitVCS dialog appears asking for username/password. Even if you check "Save Authentication" the system asks for auth on the next commit.

This appears on RabbitVCS.log:
2019-06-18 12:05:07,842 ERROR   rabbitvcs.ui.widget     SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140611390744000 and this is thread id 140611153020672.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rabbitvcs/ui/widget.py", line 855, in __init__
    gtkspell.Spell(self.view)
  File "/usr/lib/python2.7/site-packages/gtkspell.py", line 32, in __init__
    self.spellchecker = gtkspellcheck.SpellChecker(textview, language)
  File "/usr/lib/python2.7/site-packages/gtkspellcheck/spellcheck.py", line 195, in __init__
    self.languages = SpellChecker._LanguageList.from_broker(self._broker)
  File "/usr/lib/python2.7/site-packages/gtkspellcheck/spellcheck.py", line 151, in from_broker
    for language in broker.list_languages()],
  File "/usr/lib/python2.7/site-packages/gtkspellcheck/spellcheck.py", line 103, in code_to_name
    return _code_to_name(code, separator)
  File "/usr/lib/python2.7/site-packages/pylocales/locales.py", line 152, in code_to_name
    lang = Language.by_iso_639_1(code[0]).translation
  File "/usr/lib/python2.7/site-packages/pylocales/locales.py", line 138, in by_iso_639_1
    return Language.get_language(code, 'iso_639_1')
  File "/usr/lib/python2.7/site-packages/pylocales/locales.py", line 123, in get_language
    (code,)).fetchone()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140611390744000 and this is thread id 140611153020672.

Have Google about that but found nothing.

**Comment by monnerat** [comment] 2019-06-22 00:53
These are two different problems: should be 2 issues for them.
For problem 1: I assume you use an SVN repo, right ?
The authentication saving is under the responsibility of subversion itself and plaintext passwords saving is disabled by default.
The rabbitvcs "save authentication" checkbox tells svn we want to do it, but subversion may block it.
See file `~/.subversion/servers` for a description of possible parameters (in your case, probably `store-passwords`, `store-plaintext-passwords`, `store-auth-creds`)

**Comment by jcerdan** [comment] 2019-07-02 13:17
Hi,
Yes, I'm using a svn repo. I have edited ~/.subversion/servers and enabled store passwords in [global] but Atom keeps asking for auth. :-( 
I have sublime text also in teh same computer and it does not ask all the time for the auth, just the first time. This, for the same repo. 
So, it's something about Atom/SVN.
Any other clue?

**Comment by monnerat** [comment] 2019-07-03 13:48
I made some tests, without luck, although the `svn` command issued by `rabbitvcs` is perfectly correct. I've never succeeded in having `svn` storing the plaintext password in the `.subversion/auth` subdirectory. I presume your `sublime` software (that I don't know) uses its own password caching, while `rabbitvcs` does not. Even the `svn` cli tests I made did not store the password.

From the `.subversion/config` file:
```
### Set password stores used by Subversion. They should be
### delimited by spaces or commas. The order of values determines
### the order in which password stores are used.
### Valid password stores:
###   gnome-keyring        (Unix-like systems)
###   kwallet              (Unix-like systems)
###   gpg-agent            (Unix-like systems)
###   keychain             (Mac OS X)
###   windows-cryptoapi    (Windows)

```
I may be wrong, but I suppose you have to implement one of these engine to allow `svn` to save passwords. After digging in `svn` sources, I did not find anything clear and it's too complicated for me to understand it.

I did not find any workaround and I'm sorry I can't help you more. May be you should talk with some `svn` guru or look to implement some of the password store engines mentioned above (I did not test this myself).

**Comment by philippun1** [comment] 2020-04-24 18:31
I can confirm this behaviour and it can be reproduced with nautilus context menu as well.
It is definitely not a problem of subversion itself. subversion correctly stores the password and you only have to type it in the first time in the shell.
rabbitvcs however is not affected by any of the values in the .subversion/config or /etc/subversion/servers settings. I tried store-plaintext-passwords, store-passwords, store-auth-creds.

**Comment by philippun1** [comment] 2020-04-25 18:49
I did some further research. This is actually a problem of pysvn. With the latest pysvn 1.9.11 this issue is resolved.
At least for Ubuntu you can use my ppa as a workaround for now: https://launchpad.net/~philippun/+archive/ubuntu/stuff

**Comment by monnerat** [comment] 2020-04-26 15:30
I found an explanation on https://stackoverflow.com/questions/2599281/cant-make-svn-store-passwords-even-though-the-configuration-is-set-to-allow-it/17330250 (many thanks to SRG):

>  I think it's important to note that since SVN 1.12, plain text storage is disabled by default at compile time (= you have to recompile SVN by yourself if you want this feature),

In other words, if you use the stock subversion package from your distro, subversion will silently ignore keyword `store-plaintext-passwords` unless the feature has been explicitly enabled at compile time. For info, I use Fedora and it's not compiled in.

If you want to recompile subversion yourself, include option `--enable-plaintext-password-storage` in `./configure` parameters.

Pysvn uses the subversion libraries and is thus dependant of this feature's support in the subversion package.

**Comment by dtrunk90** [comment] 2020-08-11 09:21
Using the PPA from @philippun1 to upgrade package "python3-svn" to 1.9.11 worked. Thank you! I guess you can close this issue as this is/was not an issue for rabbitvcs.

**Comment by pczekalski** [comment] 2020-08-20 10:03
Many thanks! Updating to @philippun1 's version of pysvn seems to work for me.

**Comment by maxwa** [comment] 2020-09-11 03:51
Thanks @philippun1 ! Your **python3-svn** works for me too.

**Comment by frang75** [comment] 2020-10-18 17:25
Thanks @philippun1! Works fine!

**Comment by prblaylock** [comment] 2020-10-23 04:20
Thanks for the workaround @philippun1

**Comment by joellgarcia** [comment] 2021-04-14 12:34
Thanks @philippun1 
It work's

**Comment by pammel** [comment] 2021-07-23 12:48
Thanks @philippun1! Works fine!

**Closed** 2021-07-24 12:57 UTC

**Comment by Briandan1230** [comment] 2022-05-13 13:52
thanks, @philippun1, nice fix
