### ISSUE TITLE
cant signin to github

### ISSUE THREAD

**Issue by dvdknaap** [rabbitvcs/rabbitvcs#90] opened 2015-03-24 12:14 UTC
Hi all,

I can't connect to my github repo when i clone from https it says that it can't find my username thats because i got a '@' in my password an some other non alphameric.

When i use the ssh clone it doenst recognize my public key

When i use git from the command line it does work so how is rabbitvcs connecting to github and how can i fix this ?

**Comment by DutchProgrammer** [comment] 2015-03-24 12:23
After a reboot the ssh is recognized now so that part is fixed

I removed this program due to the last updates and that the file changes doesnt show up while commiting

**Comment by adamplumb** [comment] 2017-06-23 23:42
This is a duplicate of another bug and this is fixed in master.

**Closed by adamplumb** 2017-06-23 23:42 UTC
