### ISSUE TITLE
Commit error : 075 ERROR	rabbitvcs.util.__init__	

### ISSUE THREAD

**Issue by clickstefan** [rabbitvcs/rabbitvcs#157] opened 2016-05-23 07:05 UTC
When I try to commit I get 'mnt' as path
![screenshot from 2016-05-23 09-57-55](https://cloud.githubusercontent.com/assets/5954967/15462761/825be340-20cd-11e6-9bfe-19b1e75d2183.png)

where is what I get in the log

> 2016-05-23 09:57:34,701 ERROR rabbitvcs.util.**init** 
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/rabbitvcs/util/**init**.py", line 119, in start
>     func.start()
>   File "/usr/local/lib/python2.7/dist-packages/rabbitvcs/util/**init**.py", line 44, in start
>     self.result = self.func(_self.args, *_self.kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/rabbitvcs/vcs/git/**init**.py", line 535, in commit
>     commit_all)
>   File "/usr/local/lib/python2.7/dist-packages/rabbitvcs/vcs/git/gittyup/client.py", line 803, in commit
>     merge_heads=parents)
>   File "/usr/lib/python2.7/dist-packages/dulwich/repo.py", line 549, in do_commit
>     c.tree = index.commit(self.object_store)
>   File "/usr/lib/python2.7/dist-packages/dulwich/index.py", line 309, in commit
>     return commit_tree(object_store, self.iterblobs())
>   File "/usr/lib/python2.7/dist-packages/dulwich/index.py", line 349, in commit_tree
>     return build_tree(b'')
>   File "/usr/lib/python2.7/dist-packages/dulwich/index.py", line 343, in build_tree
>     sha = build_tree(pathjoin(path, basename))
>   File "/usr/lib/python2.7/dist-packages/dulwich/index.py", line 340, in build_tree
>     for basename, entry in trees[path].items():
> KeyError: 'mnt'

the path that I tried to commit is '/symlink/src/Some_Path/Sub_Folder' that points to '/mnt/.../src/Some_Path/Sub_Folder'

**Comment by joostverburg** [comment] 2016-07-29 19:43
I noticed the same issue when committing files. It looks like files are being staged with an absolute path instead of a relative path.

I think the line `to_stage.append(path)` in rabbitvcs/vcs/git/gittyup/client.py may be the cause. Try to replace it with `to_stage.append(relative_path)`.

**Comment by adamplumb** [comment] 2017-06-21 01:30
This should be fixed now.

**Closed by adamplumb** 2017-06-21 01:30 UTC
