### ISSUE TITLE
Log filter not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by Megamouse** [rabbitvcs/rabbitvcs#320] opened 2020-10-29 09:37 UTC
Hi. I can't filter the svn log dialog on Ubuntu 20.04.

![image](https://user-images.githubusercontent.com/23019877/97550735-54b66c00-19d2-11eb-95ba-63f52e69cca4.png)

I am sure that it worked on my older Ubuntu 16.04 install.
But since we upgraded our workstations to Ubuntu 20.04 at work, I can't filter anymore.
I can't even click the input field, which means I can't enter any text.
The Limit input field works though, so maybe it helps for debugging:

![image](https://user-images.githubusercontent.com/23019877/97550858-7dd6fc80-19d2-11eb-8fb1-838fdaa2abfa.png)

My setup:

![image](https://user-images.githubusercontent.com/23019877/97550073-7b27d780-19d1-11eb-8ff3-dfeee8d74a70.png)
![image](https://user-images.githubusercontent.com/23019877/97550254-b6c2a180-19d1-11eb-979b-5accaab2ffe4.png)
![image](https://user-images.githubusercontent.com/23019877/97550356-dfe33200-19d1-11eb-8490-9724ce65da54.png)

**Comment by AlexFolland** [comment] 2020-11-14 00:01
I'm seeing the same issue in Manjaro 20.2 running Nemo.  Clicking the search field does nothing.

On top of that, pressing the up arrow key or down arrow key with a log entry highlighted doesn't update the selected log entry, so I have to click each log entry as a workaround.

Also, the text in the list of log entries is black on a dark background here, so reading it is literally painful.

These 3 issues together make RabbitVCS extremely unwieldly to use to search in SVN history in my project which has tens of thousands of commits.

RabbitVCS has the potential to be a great project and even come close to catching up with TortoiseSVN if these issues are resolved.  Thanks for all your voluntary work on it.

**Comment by JorisHansMeijer** [comment] 2021-03-30 17:37
Hi All,
I had the same problem. However I found a solution:
1. In the python source change the xml file: rabbitvcs/ui/xml/log.xml remove line 319 (can_focus propety for search_buffer),
2. In the file rabbitvcs/ui/log.py change line 194
from: self.filter_text = tb.get_text(tb.get_start_iter(), tb.get_end_iter()).lower()
to:     self.filter_text = tb.get_text(tb.get_start_iter(), tb.get_end_iter(), 0).lower()

That is all :)

**Comment by metal450** [comment] 2021-04-16 20:00
> Hi All,
> I had the same problem. However I found a solution:
> 
>     1. In the python source change the xml file: rabbitvcs/ui/xml/log.xml remove line 319 (can_focus propety for search_buffer),
> 
>     2. In the file rabbitvcs/ui/log.py change line 194
>        from: self.filter_text = tb.get_text(tb.get_start_iter(), tb.get_end_iter()).lower()
>        to:     self.filter_text = tb.get_text(tb.get_start_iter(), tb.get_end_iter(), 0).lower()
> 
> 
> That is all :)

Awesome, I can confirm that this fixes the ability to search!

If u have the ability, it would be amazing to also have a fix for: 

> On top of that, pressing the up arrow key or down arrow key with a log entry highlighted doesn't update the selected log entry, so I have to click each log entry as a workaround.

:)

**Comment by JorisHansMeijer** [comment] 2021-04-18 10:11
I have found a fix for this issue as well. You can find it in the pull 
requests section.

**Comment by metal450** [comment] 2021-04-18 16:26
Nice, it works!!!

I know this isn't related, but since it seems you're pretty familiar with the codebase, I wonder if you might take a quick peek at https://github.com/rabbitvcs/rabbitvcs/issues/258? It's the only remaining day-to-day major issue, that Rabbit is never able to delete/remove files from Git. To delete anything requires explicitly doing so from the cli, then one can return to rabbit for other (working) features.  If it's feasible, would be super awesome. Literally the only remaining broken thing I'm aware of :)

**Comment by CloCkWeRX** [comment] 2021-04-28 04:52
Thanks @JorisHansMeijer for the fix!

**Closed** 2021-04-28 04:51 UTC
Labels: bug
