### ISSUE TITLE
Trying to export a file from SVN-repo browser deletes target directory

### ISSUE THREAD

**Issue by erihe251** [rabbitvcs/rabbitvcs#127] opened 2015-12-02 09:40 UTC
I noticed that when I try to export a file from within the SVN-repo browser, the operation fails and the target directory is deleted. Maybe I'm missing something, but this seems like a harsh way of failing. 

I discovered it when doing a quick export to a temp folder, so not too bad. But others might not be so lucky.

Using RabbitVCS 0.16 with thunar-plugin on Fedora 23.

Before:
![before](https://cloud.githubusercontent.com/assets/2757705/11526762/0eed9bd8-98dd-11e5-97e2-ce8fba1d245c.png)

After:
![after](https://cloud.githubusercontent.com/assets/2757705/11526763/10f2f8a6-98dd-11e5-9faf-a38657400180.png)

**Comment by xethm55** [comment] 2015-12-03 20:35
I have the exact same issue also with rabbitvcs 0.16 and thunar on Majaro though.

**Comment by RosemarysBaby** [comment] 2016-04-19 10:05
THis just happened to me as well. Harsh way is mildly worded though :)

**Comment by MartinBorg** [comment] 2016-07-26 14:03
This bug seems highly severe to me. At least two users lost their complete home directories:

https://bugs.debian.org/817231

http://askubuntu.com/questions/473433/rabbitsvn-deleted-all-my-folders

Any ideas what to do about it other than warn people not to use RabbitVCS?

**Comment by kwill** [comment] 2016-07-27 11:38
Suggestion:

**Comment by erihe251** [comment] 2016-08-01 16:33
I agree that this is a showstopper. 
Quick fix could be to preface the export dialog with a warning prompt.

**Comment by mans0954** [comment] 2016-08-27 17:23
Appears to be a duplicate of #70 , fixed in #89

**Comment by iandiver** [comment] 2016-12-25 17:02
This bug is still present in version 0.16.0! It would be so very helpful if a prompt to overwrite the existing file could be added, at least this would highlight what is about to happen. To me this would be the "reasonable thing to do".

I just trashed my Downloads folder (thankfully not my entire home directory). The export dialog window says "Select Folder", so I did, not realizing this meant "this is the file I will overwrite if it already exists". Many, many people run into this obvious issue. Please can the subject matter expert spend 15 minutes adding this check, or point me to making the change and I'll do it.

Many thanks.

**Comment by adamplumb** [comment] 2017-06-18 16:40
This looks to be fixed now.

**Closed by adamplumb** 2017-06-18 16:40 UTC
