### ISSUE TITLE
Git - Credentials not stored

### ISSUE THREAD

**Issue by pablorq** [rabbitvcs/rabbitvcs#324] opened 2021-02-19 12:05 UTC
When using Git, credentials are not stored.

## System
- Ubuntu 20.10
- Nautilus 3.38.1-stable
- RabbitVCS 0.18
- Subversion - 1.14.0.
- Pysvn - 1.9.12.0
- ConfigObj - 5.0.6

## History
Related issues:
#270 - Rabbitvcs keeps asking for username/password on each commit, using it under Atom Editor
#310 - SVN credentials not stored

Both did reference to a problem on `pysvn`, which was solved by a workaround involving a PPA.

But the base of the problem was related to `pysvn` or `python3-svn` version 1.9.11.

Now in my system (clean install of Ubuntu 20.10) I have `python3-svn` version 1.9.12-1, and the problem is again there.

## Help wanted

Any idea how to solve this problem?

**Comment by monnerat** [comment] 2021-04-14 22:23
Your problem seems to be with subversion, not git: maybe you want to change the title of this issue !

Please read comment https://github.com/rabbitvcs/rabbitvcs/issues/270#issuecomment-619570306: this is the real source of the problem and is not related to a distro-specific workaround. You probably have to recompile subversion yourself or file a bug to Ubuntu.

IMHO, this issue is a duplicate of #270, Closing.

**Closed by monnerat** 2021-04-14 22:23 UTC
